/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface SortDropdownProps {
  label: string;
  value: string;
}

const SortDropdown: React.FC<SortDropdownProps> = ({ label, value }) => {
  return (
    <div className="flex overflow-hidden gap-1 justify-center items-center py-1 pr-1 pl-3 bg-white rounded-md border border-solid border-zinc-200">
      <div className="flex gap-2 items-center self-stretch my-auto">
        <div className="self-stretch my-auto text-gray-400">{label}</div>
        <div className="self-stretch my-auto text-gray-800">{value}</div>
      </div>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/6b071eaf30b57fc1f726f95565e9730a0781d42f3a0bef11770573f10c8bbe2f?placeholderIfAbsent=true&apiKey=bc78d96b1bfe4229ab8bdab79a935f37"
        alt=""
        className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
      />
    </div>
  );
};

export default SortDropdown;
