/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SearchHeader: React.FC = () => {
  return (
    <div className="text-2xl font-semibold tracking-tight leading-none text-blue-700">
      <span className="">Found 376 results for </span>
      <span className="text-blue-700">qwerty</span>
    </div>
  );
};

export default SearchHeader;
