/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface LogoProps {
  src: string;
  companyName: string;
  tagline: string;
}

const Logo: React.FC<LogoProps> = ({ src, companyName, tagline }) => {
  return (
    <div className="flex flex-col self-stretch my-auto h-[131px] w-[169px]">
      <img
        loading="lazy"
        src="Group 7610.png"
        alt={`${companyName} logo`}
        className="object-contain self-center w-24 aspect-[1.02]"
      />
      <div className="flex flex-col justify-center mt-3 w-full">
        <div className="self-center text-2xl font-black leading-none text-center">
          {companyName}
        </div>
        <div className="text-lg font-light leading-loose text-right">
          {tagline}
        </div>
      </div>
    </div>
  );
};

export default Logo;
